"""增加章节内容字段

Revision ID: 891ae81e9873
Revises: 4e61345a8f3d
Create Date: 2025-04-09 23:31:43.623257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891ae81e9873'
down_revision: Union[str, None] = '4e61345a8f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('content', sa.Text(), nullable=True))
    op.drop_index('scenes_summary_embedding_idx', table_name='scenes', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('scenes_summary_embedding_idx', 'scenes', ['summary_embedding'], unique=False, postgresql_using='hnsw')
    op.drop_column('chapters', 'content')
    # ### end Alembic commands ###
